org: chughes87
app: calendarbot
service: calendarbot

frameworkVersion: '3'

configValidationMode: error

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - secretsmanager:GetSecretValue
      Resource: <SECRET_ARN>

functions:
  dailyCron:
    handler: src/eventHandler.daily
    events:
      - schedule: cron(30 21 * * ? *)
    environment:
      TZ: America/Los_Angeles
  hourlyCron:
    handler: src/eventHandler.hourly
    events:
      - schedule: cron(45 * * * ? *)
    environment:
      TZ: <YOUR_TIMEZONE>
