org: chughes87
app: calendarbot
service: calendarbot

frameworkVersion: '3'

configValidationMode: error

package:
  patterns:
    - src/**

custom:
  TZ: <YOUR_TIMEZONE>
  layerArn: <LAYR_ARN>
  secretArn: <SECRET_ARN>

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-1
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - secretsmanager:GetSecretValue
          Resource: ${self:custom.secretArn}

layers:
  calendarbotdeps:
    path: ../calendarbot-layer
    compatibleRuntimes: nodejs14.x

functions:
  dailyCron:
    handler: src/eventHandler.daily
    events:
      - schedule: cron(30 4 * * ? *)
    environment:
      TZ: ${self:custom.TZ}
    layers:
      - { Ref: CalendarbotdepsLambdaLayer}
  hourlyCron:
    handler: src/eventHandler.hourly
    events:
      - schedule: cron(45 * * * ? *)
    environment:
      TZ: ${self:custom.TZ}
    layers:
      - { Ref: CalendarbotdepsLambdaLayer}
  weeklyHandler:
    handler: src/eventHandler.weekly
    environment:
      TZ: ${self:custom.TZ}
    layers:
      - { Ref: CalendarbotdepsLambdaLayer}
